[package]
name = "suds"
version = "0.1.0"
authors = ["mchlrhw <4028654+mchlrhw@users.noreply.github.com>"]
edition = "2018"

[dependencies]
clap = { git = "https://github.com/clap-rs/clap/" }
crossterm = "0.16"
fehler = "1.0.0-alpha.2"
